// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCN9BE4F2KyyofEC3dsirAyw0ZEklSif8',
    appId: '1:645576145768:web:cb1bc557de467f57dc74dd',
    messagingSenderId: '645576145768',
    projectId: 'wegrow-a121c',
    authDomain: 'wegrow-a121c.firebaseapp.com',
    storageBucket: 'wegrow-a121c.firebasestorage.app',
    measurementId: 'G-02QK9CLSFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB81Ilavav_RcIpxI4Zfa0Ghvj7ajWAas',
    appId: '1:645576145768:android:b89cb5387037cf22dc74dd',
    messagingSenderId: '645576145768',
    projectId: 'wegrow-a121c',
    storageBucket: 'wegrow-a121c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCICHhvuWTJ24LBETmq947mO2nOrtKlrGE',
    appId: '1:645576145768:ios:b54db9fe6cf57478dc74dd',
    messagingSenderId: '645576145768',
    projectId: 'wegrow-a121c',
    storageBucket: 'wegrow-a121c.firebasestorage.app',
    iosBundleId: 'com.wegrowbranding.akfcustomer',
  );
}
